winget install -e --id 7zip.7zip
winget install -e --id Discord.Discord
winget install -e --id Docker.DockerDesktop
winget install -e --id Git.Git
winget install -e --id Google.Chrome
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Nvidia.GeForceExperience
winget install -e --id OBSProject.OBSStudio
winget install -e --id OpenJS.NodeJS.LTS
winget install -e --id Oracle.JavaRuntimeEnvironment
winget install -e --id Oracle.JDK.17
winget install -e --id Python.Python
winget install -e --id REALiX.HWiNFO
winget install -e --id Rufus.Rufus
winget install -e --id Spotify.Spotify
winget install -e --id Valve.Steam
winget install -e --id VideoLAN.VLC
winget install -e --id qBittorrent.qBittorrent
winget install -e --id WinDirStat.WinDirStat
winget install -e --id TeamViewer.TeamViewer
winget install -e --id Audacity.Audacity
winget install -e --id Brave.Brave
